runs:
  using: "composite"
  steps:
    - name: Step 1 of setup
      run: echo "step 1"
      shell: bash
    - run: echo ${{ matrix.os }}
      shell: bash
    - run: echo ${{ matrix.go }}
      shell: bash
