on: 
  repository_dispatch:
    types: [ my-event ]

jobs:
  myEvent:
    name: Fake workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo "Hello World!"
