on: [ push ]

jobs:
  unit:
    name: Trigger multiple runs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        counter: [ 1, 2, 3 ]
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          event-type: my-event
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
