name: Tag Push Checker
on:
  push:
    tags:
      - v*

env:
  ISSUE_TITLE: "manual release created (%tagname%)"
  ISSUE_ASSIGNEE: "%pusher%"
  ISSUE_BODY: |
    @{{ env.PUSHER }} just pushed a release tag: {{ env.TAGNAME }}.
    Please manually verify validity (using [\`gorelease\`](https://pkg.go.dev/golang.org/x/exp/cmd/gorelease)), and update \`version.json\` to reflect the manually released version, if necessary.
    In the future, please use the automated process.

jobs:
  tagpush:
    runs-on: ubuntu-latest
    name: All
    env:
      TAGNAME: ""
    steps:
      - uses: actions/checkout@v2
      - run: cat "$GITHUB_EVENT_PATH" | jq -M .
      - name: extract tag name
        run: |
          tagname=$(echo "${{ github.ref }}" | sed "s/refs\/tags\///")
          echo $tagnmae
          echo "TAGNAME=$tagname" >> $GITHUB_ENV
      - name: create issue template file
        if: ${{ github.event.pusher.name != 'web3-bot' }}
        run: |
          echo "---" >> .github/workflows/tagpush.md
          echo "title: test" >> .github/workflows/tagpush.md
          echo "---" >> .github/workflows/tagpush.md
          echo "body" >> .github/workflows/tagpush.md
      - run: cat .github/workflows/tagpush.md
      - run: echo ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ secrets.token }}
      - run: echo ${{ inputs.username }}
      - run: echo ${{ github.event.pusher.name }}
      - name: create an issue
        if: ${{ github.event.pusher.name != 'web3-bot' }}
        uses: JasonEtco/create-an-issue@9e6213aec58987fa7d2f4deb8b256b99e63107a2 # v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUSHER: ${{ github.event.pusher.name }}
        with:
          filename: .github/workflows/tagpush.md
      - name: fail build if push wasn't done by web3-bot
        if: ${{ github.event.pusher.name != 'web3-bot' }}
        run: exit 1
